### ISSUE TITLE
How to run? 

### ISSUE THREAD

**Issue by Spritan** [Arjun31415/Firefly-cli#1]
(base) ➜  Firefly-cli git:(main) cargo run
warning: method `set_colors` is never used
  --> src/main.rs:62:12
   |
44 | impl Firefly {
   | ------------ method in this implementation
...
62 |     pub fn set_colors(&mut self, colors: Vec<String>) {
   |            ^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `Firefly-cli` (bin "Firefly-cli") generated 1 warning
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/Firefly-cli`
error: the following required arguments were not provided:
  --effect <EFFECT>

Usage: Firefly-cli --effect <EFFECT>

For more information, try '--help'.

installation

trail:
(base) ➜  Firefly-cli git:(main) Firefly-cli --help
zsh: Firefly-cli: command not found...

**Comment by Arjun31415** [comment]
you have to write the relative path to the binary. you cannot just use `firefly-cli`  which is why it says command not found. 
an easy way - 
```sh
cargo build 
./target/debug/Firefly-cli --colors="#f7768e","#9ece6a","#e0af68","#7aa2f7","#bb9af7","#7dcfff","#ff9e64" -e ripple
```
use the `--help` command for more info

**Comment by Arjun31415** [comment]
With `cargo run` you need to use `--` to pass arguments to the executable otherwise they are interpreted by `cargo`. 
Ex: 
```
cargo run -- -e ripple
```
